export const PYTHON_PROMPT_LIST = [
  "hello",
  "dict_example = {'a': 1, 'b': 2}\nprint(dict_example.get('a'))",
  's = "hello world"\nprint(s[::-1])',
  "print([i for i in range(10) if i % 2 == 0])",
];

export const JAVASCRIPT_PROMPT_LIST = [
  "console.log('hello world!');",
  "const add = (a, b) => a + b;",
  "const arr = [1, 2, 3, 4, 5];",
  "const factorial = n => n === 0 ? 1 : n * factorial(n - 1);",
  "const nums = [1, 2, 3, 4];\nconst squared = nums.map(x => x * x);",
  "const person = {name: 'Alice', age: 30};",
  "const str = 'hello';",
  "const isEven = num => num % 2 === 0;",
  "const numbers = [10, 20, 30];\nnumbers.forEach(num => console.log(num * 2));",
  "const obj = {x: 10, y: 20};.keys(obj));",
  "const nums = [1, 2, 3, 4, 5];\nconst evens = nums.filter(x => x % 2 === 0);",
  "const nums = [1, 2, 3, 4, 5];\nconst doubled = nums.map(x => x * 2);",
  "const nums = [1, 2, 3, 4, 5];\nconst sum = nums.reduce((acc, curr) => acc + curr, 0);",
  "const str = 'hello world';\nconst reversed = str.split('').reverse().join('');",
  "const arr = [1, 2, 3, 4];ludes(3));",
  "const numbers = [10, 20, 30];\nconst total = numbers.reduce((acc, num) => acc + num, 0);",
  "const x = 5;\nconst y = 10;g(x * y);",
  "const greet = name => `Hello, ${name}!`;greet('Alice'));",
  "const numbers = [10, 20, 30];\nconst product = numbers.reduce((acc, num) => acc * num, 1);",
  "const nums = [1, 2, 3, 4, 5];\nconst squared = nums.map(x => x ** 2);",
  "const numbers = [1, 2, 3, 4, 5];th.max(...numbers));",
];
